name: Proof HTML

on:
  workflow_run:
    workflows: ["CI", "CLI Linux", "CLI Windows", "Portable Windows"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Run HTML Proof
        uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
